### ISSUE TITLE
Avoid svg components duplication

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-incubator#44]
* **Do you want to request a *feature* or report a *bug*?**
A performance improvement.

* **What is the current behavior?**
SVG voltage level diagram is made of individual SVG components, wires and busbar sections assembled together.  SVG component are copied in to final SVG, so it means that if we have 10 loads in the substation the SVG symbol of the load is duplicated 10 times.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

* **What is the expected behavior?**
We could reduce the size of the substation SVG by using "refs/use" feature of SVG [https://developer.mozilla.org/fr/docs/Web/SVG/Element/use](https://developer.mozilla.org/fr/docs/Web/SVG/Element/use) to avoid duplicating component SVG.
This new feature has to be optional (a parameter in `LayoutParameters`), because JavaFX SVG rendering library probably (to check) don't support "refs/use".

* **What is the motivation / use case for changing the behavior?**
Reduce the SVG size and consequently increase rendering performance.

* **Please tell us about your environment:**
  - PowSyBl Version: 2.5.0-SNAPSHOT
  - OS Version: Linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by CBiasuzzi** [comment]
when parameter avoidSVGComponentsDuplication is set, is it expected that
a lot of elements end up duplicated in the "defs" section?
e.g. in substation-diagram/substation-diagram-core/src/test/resources/TestCase12GraphVL1_optimized.svg, defs section,
there are multiple copies, for the same component type ...

**Comment by FranckLecuyer** [comment]
You're right.
In fact, it's a regression introduced by issue https://github.com/powsybl/powsybl-incubator/issues/157, which leads to the suppression of the ComponentType enum
I correct that immediatly
Thanks for your comment ...
