### ISSUE TITLE
Topological style provider

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-incubator#60]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the expected behavior?**
We need a `SubstationDiagramStyleProvider` implementation (`TopologySubstationDiagramStyleProvider`) that color the voltage level according to topology => one color per bus.
Using feature added  by #40, we can generate a color scale for each base voltage (so color close to base voltage one) that will be used for bus coloring.

For instance, if we have a 400Kv voltage levels with 2 buses. We need to color differently the 2 buses. If we have defined the color for 400Kv base voltage as red we need to use 2 different variants of the red for the 2 buses.
I think this can be done automatically with something [like](https://hihayk.github.io/scale/#4/6/50/80/-51/67/20/14/FF0000/255/0/0)
 
* **What is the motivation / use case for changing the behavior?**
To see the topology.

**Comment by sylvlecl** [comment]
In the link above, we can play with "HSB" offsets (Hue, Saturation, Brightness).
JavaFX `Color` class has a [method](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/paint/Color.html#deriveColor-double-double-double-double-) to do exactly this.

We can probably use those HSB offsets as parameters for this feature.
